### ISSUE TITLE
[Feature Request] polygon file filtering

### ISSUE THREAD

**Issue by farfromrefug** [protomaps/tippecanoe#15]
i would like to have the same feature as the one we are adding to planetiler https://github.com/onthegomap/planetiler/pull/280

The idea is to reduce mbtiles size
I know i can already do that with -C but it is amazingly slow because the script is called on each x/y/z and i cant really easily cache the polygon object to quickly test if a tile is within the polygon.

I think the best would be for this to be implemented in tippecanoe

**Comment by bdon** [comment]
can you preprocess your input? Tippecanoe does not work with OSM input so a .POLY file doesn't make sense; your dataset should exist first in a format like SHP, GeoJson, GeoJsonSeq or FlatGeobuf which you should be able to spatially filter with general-purpose tools.

**Comment by bdon** [comment]
I would prefer not to implement this feature in tippecanoe itself but instead let another tool handle spatial filtering of your GeoJSON, which is very general and not specific to tile generation. It also involves some small decisions like whether or not geometries that cross the boundary of the polygon should be clipped.

**Comment by farfromrefug** [comment]
@bdon i already have that but as i explained it will be dead slow if handled outside of tippecanoe as tippecanoe calls a script on each x/y/z.
In python we create an optimised geometry to make test fast. but  i cant do that when you call a script on each x/y/z

**Comment by bdon** [comment]
I meant you can write a Shapely program that takes your GeoJSON as input and outputs a new GeoJSON filtered to the geometry, and then pass the filtered GeoJSON into tippecanoe; I agree the `-C` option is not well suited to this use case

**Comment by farfromrefug** [comment]
@bdon i am not sure i understand. To be clear the idea is to have a geometry for filtering which is not an rectangle like bbox but any polygon . I dont understand how tippecanoe would use that filter `GeoJSON` ?

**Comment by bdon** [comment]
you can write a python program totally separate from tippecanoe that reads your GeoJSON (or any format with Fiona), and then uses Shapely `intersects` https://shapely.readthedocs.io/en/stable/manual.html#object.intersects to write out a new GeoJSON file with only those that intersects the polygon.

**Comment by farfromrefug** [comment]
@bdon ok this is already what i do. The issue is that it is really slow because operations on the shape to make it faster (like simplification based on zoom) have to be done on each script call.
I was hoping tippecaone could handle this since it already supports bbox and it would be so much faster.

**Comment by bdon** [comment]
Steps to making this work in tippecanoe:
1) decide on an input format for the area of interest (multi?)-polygon, probably GeoJSON only
2) may need to validate that the input multi polygon is Simple and Valid
3) for every point in every input feature do a point-in-polygon test against the AOI, only writing the feature to serial disk stat if it passes

This would mean that even a polygon that barely touches your boundary would be included; doing clipping of arbitrary geometries (lines, polygons) to the AOI is much more difficult but might be more like what you want

In any case, step 3 is going to be slow no matter what since the PIP test is O(# of vertices in the AOI) * vertices in the input, unless we build some fancier acceleration structure, which may require bringing in a different library

**Comment by farfromrefug** [comment]
@bdon yes this is what i want. even the smallest intersection should be included. This is required when you want to "divide" like the world mbtiles into small dowloadable regions. You want each region to be as small as possible but still have only full tiles (event at "borders"). This is why i started the PR in planetiler: use like europe pbf to generate france with the .poly to limit.
In tippecanoe i do the same thing by using a bigger geotif.

You are right about the complexity i already have it in rio-rgbify (have the code locally, need to create the PR).

**Comment by bdon** [comment]
I have already implemented polygon filtering at the OSM source level at https://protomaps.com/downloads/osm which will act directly on OSM files; because the data there is already spatially indexed it can be performed much more efficiently than at the tippecanoe step. So since there are so many ways to do spatial filtering I am unsure if it fits into the responsibilities of tippecanoe, given that it is fairly minimal and dependency-free as is.

**Comment by farfromrefug** [comment]
@bdon interesting your filtering keeps data so that all tiles are full?
Btw @msbarry just changed the implementation for planetiler. Instead he generated the full list of tiles that a geometry intersects. Then the check is a as simple as "contains".
I think i could use that technique to make it fast  with `-C`:
* on each script run:
* check if we already generated the list of tiles for the geometry into a file (hash of the geeometry).
* generate if not
* read the file and check if contains

So i guess it would be fast enough. That way tippecanoe does not have to implement this.

Will try to implement it in python so that i can use it in rio-rgbify and with tippecanoe

Thanks for taking the time, i gues we can close this

**Comment by bdon** [comment]
the filtering there uses S2 cells which are the appropriate spatial index format for non-projected geographic coordinates. 

The approach you mentioned is generating a total tileset covering of the AOI polygon, and then generating only tiles that are part of that tileset. That would be much faster, but would still need a bit of code to generate the initial tileset from the AOI. Maybe others would be interested in this feature?

**Comment by farfromrefug** [comment]
@bdon yes you are right. And i am not that good with geospatial stuff :D Will try to write it in python then we could publish it.
You want to help ? :P you seem really good with all that :D
